### ISSUE TITLE
Rails 7

### ISSUE THREAD

**Issue by lreddickGNA** [salsify/delayed_job_worker_pool#14]
I walked through all the code in this gem and I don't see anything that would be deprecated in Rails 7- do we know if it's good for Rails 7 for sure? If so, the gemspec dependencies should be update to reflect `< 8` for `rails` versions.

**Comment by will89** [comment]
Currently, we do not know if it's ready for rails 7. I'll look into updating the build matrix for this gem to test against it. In the meantime, since the rails dependency is only in the development_dependencies I think you should be able to bundle install this with rails 7 for using/testing with your application.

**Comment by will89** [comment]
Added testing in https://github.com/salsify/delayed_job_worker_pool/pull/15.
